#ifndef WEB_CONTENT_H
#define WEB_CONTENT_H

const char* html_content = "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Microcontroller Interface</title><link rel=\"stylesheet\" href=\"style.min.css\"></head><body><div class=\"tab-header\"><button class=\"tab-button active\" onclick='openTab(\"serial\")'>Serial Interface</button> <button class=\"tab-button\" onclick='openTab(\"upload\")'>File Upload</button> <button class=\"tab-button\" onclick='openTab(\"settings\")'>Settings</button></div><div id=\"serial\" class=\"tab active\"><input type=\"text\" id=\"inputField\" placeholder=\"Type here...\"> <button onclick=\"submitData()\">Submit</button> <button onclick=\"clearOutput()\">Clear Output</button> <label><input type=\"checkbox\" id=\"autoScroll\" checked=\"checked\"> Scroll to bottom</label><div id=\"output\"></div></div><div id=\"upload\" class=\"tab\"><h2>Upload</h2><form id=\"upload-form\" action=\"/upload\" method=\"post\" enctype=\"multipart/form-data\"><input type=\"file\" name=\"file\"> <input type=\"submit\" value=\"Upload File\"></form><h2>Files</h2><button id=\"delete-selected\">Delete Selected Files</button><div id=\"file-list\"><table id=\"files-table\"><thead><tr><th>Select</th><th>File Name</th><th>Size</th></tr></thead><tbody></tbody></table></div></div><div id=\"settings\" class=\"tab\"><div style=\"display:grid;grid-template-columns:auto auto;gap:10px\"><div>Setting 1</div><input type=\"text\"></div></div><script src=\"script.min.js\"></script></body></html>";

const char* css_content = "body{font-family:Arial,sans-serif;margin:0;padding:20px;box-sizing:border-box}.tab{display:none}.tab.active{display:block}.tab-header{margin-bottom:20px}.tab-button{padding:10px;cursor:pointer}.tab-button.active{font-weight:700}#inputField{width:calc(100% - 10px);box-sizing:border-box}#output{height:calc(100vh - 220px);overflow-y:scroll;background:#f0f0f0;margin-top:10px;padding:5px;font-family:'Courier New',monospace;white-space:pre}button{margin-top:5px}";

const char* js_content = "var uploadForm=document.getElementById(\"upload-form\"),deleteSelected=document.getElementById(\"delete-selected\"),inputField=document.getElementById(\"inputField\"),output=document.getElementById(\"output\"),autoScroll=document.getElementById(\"autoScroll\"),cmdHist=[],cmdHistIndex=0;function openTab(e){for(var t,n=document.getElementsByClassName(\"tab\"),d=0;d<n.length;d++)n[d].style.display=\"none\";for(t=document.getElementsByClassName(\"tab-button\"),d=0;d<t.length;d++)t[d].className=t[d].className.replace(\" active\",\"\");document.getElementById(e).style.display=\"block\",event.currentTarget.className+=\" active\"}function submitData(){var e=inputField.value;cmdHist.push(e),cmdHistIndex=cmdHist.length,fetch(\"/submit\",{method:\"POST\",body:e}),inputField.value=\"\"}function clearOutput(){output.innerHTML=\"\"}function poll(){fetch(\"/poll\").then(e=>e.json()).then(e=>{var t=autoScroll.checked&&output.scrollTop+output.clientHeight===output.scrollHeight;e.forEach(e=>{var t=document.createElement(\"div\");t.textContent=\"\"!=e?e:\" \",output.appendChild(t)}),t&&(output.scrollTop=output.scrollHeight)})}function fetchAndDisplayFiles(){fetch(\"/list-files\").then(e=>e.json()).then(e=>{const n=document.querySelector(\"#files-table tbody\");n.innerHTML=\"\",e.forEach(e=>{var t=document.createElement(\"tr\");t.innerHTML=`\n                    <td><input type=\"checkbox\" class=\"file-checkbox\" data-filename=\"${e.name}\"></td>\n                    <td><a href=\"/download?filename=${encodeURIComponent(e.name)}\">${e.name}</a></td>\n                    <td>${e.size} bytes</td>\n                `,n.appendChild(t)})})}function downloadFile(e){window.open(\"/download?filename=\"+encodeURIComponent(e),\"_blank\")}inputField.addEventListener(\"keydown\",function(e){\"Enter\"===e.key?submitData():\"ArrowUp\"===e.key?(cmdHistIndex=Math.max(cmdHistIndex-1,0),inputField.value=cmdHist[cmdHistIndex]||\"\"):\"ArrowDown\"===e.key&&(cmdHistIndex=Math.min(cmdHistIndex+1,cmdHist.length-1),inputField.value=cmdHist[cmdHistIndex]||\"\")}),uploadForm.addEventListener(\"submit\",function(e){e.preventDefault();e=new FormData(uploadForm);fetch(\"/upload\",{method:\"POST\",body:e}).then(e=>{e.ok?fetchAndDisplayFiles():alert(\"Upload failed\")}).catch(e=>console.error(\"Error:\",e))}),deleteSelected.addEventListener(\"click\",()=>{var e=Array.from(document.querySelectorAll(\".file-checkbox:checked\")).map(e=>e.dataset.filename);0<e.length&&confirm(\"Are you sure you want to delete the selected files?\")&&e.forEach(e=>{fetch(\"/delete-file\",{method:\"POST\",headers:{\"Content-Type\":\"text/plain\"},body:e}).then(()=>fetchAndDisplayFiles())})}),document.addEventListener(\"DOMContentLoaded\",fetchAndDisplayFiles),setInterval(poll,2e3);";

#endif // WEB_CONTENT_H
